services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: zero-to-one-api
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://${DB_USERNAME:-postgres}:${DB_PASSWORD:-password}@postgres:5432/${DB_DATABASE:-zero_to_one}?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
      - redis
    networks:
      - zero-to-one-network

  postgres:
    image: postgres:16-alpine
    container_name: zero-to-one-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-zero_to_one}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zero-to-one-network

  redis:
    image: redis:7-alpine
    container_name: zero-to-one-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - zero-to-one-network

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: zero-to-one-redis-ui
    ports:
      - '8001:8001'
    depends_on:
      - redis
    networks:
      - zero-to-one-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: zero-to-one-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - zero-to-one-network

networks:
  zero-to-one-network:
    driver: bridge

volumes:
  postgres_data:
