services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: zero-to-one-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-zero_to_one}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cache Redis pour le TenantService
  redis:
    image: redis:7-alpine
    container_name: zero-to-one-redis
    restart: always
    ports:
      - '6379:6379'

  # Interface pour visualiser Redis (Optionnel mais génial en dev)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: zero-to-one-redis-ui
    ports:
      - '8001:8001'
    depends_on:
      - redis

volumes:
  postgres_data:
