services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zero-to-one-api
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env 
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CORS_ORIGINS: ${CORS_ORIGINS}
    depends_on:
          postgres:
            condition: service_healthy
          redis:
            condition: service_started
    networks:
      - zero-to-one-network

    command: sh -c "npx prisma migrate deploy && npx prisma generate && node dist/src/main.js"

  postgres:
    image: postgres:16-alpine
    container_name: zero-to-one-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-zero_to_one}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zero-to-one-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: zero-to-one-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - zero-to-one-network

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: zero-to-one-redis-ui
    ports:
      - '8001:8001'
    depends_on:
      - redis
    networks:
      - zero-to-one-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: zero-to-one-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - zero-to-one-network

networks:
  zero-to-one-network:
    driver: bridge

volumes:
  postgres_data:
